spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Deivyd1995/Backend-micorservicios-final
          default-label: main

server:
  port: 8888
